### ISSUE TITLE
API Schools.by недоступен

### ISSUE THREAD

**Issue by Neitex** [f69/school#1]
Schools.by отключили свой API недавно. Вследствие этого, ни одно приложение для Schools.by (за исключением их сайта) не работает. (т.к. "дзённiк" построен на этом API - он тоже не работает)

**Comment by TimTProd** [comment]
так с сайта и парсь) зачем тут api

**Comment by Neitex** [comment]
Пусть это и дёргание мёртвого треда, но всё же.
1. API более надёжен с точки зрения неизменности - при любом изменении даже дизайна сайта все парсеры могут слететь (например, могут поменяться названия классов), тогда как API меняется раз в никогда (или же, как в случае с дзёнником - раз в ~6 лет :) )
2. API предоставляет больше данных в одном запросе - в силу специфики одного из моих проектов, связанных со Schools.by, необходимы такие поля, как "lesson_id" и "journal_id". Получать эти данные методом парсинга - очень костыльный и, что самое печальное, неточный способ. Например, уроки по подгруппам - для того, что бы получить ID урока и ID журнала для конкретного урока конкретного ученика методом парсинга нужно пропарсить **все** журналы предмета (например, для физики в классе, состоящем из двух профилей (рус-мат и физ-мат) без привязки к контексту конкретного класса (т.е. полностью автоматизированно одним и тем же алгоритмом для всех классов) нужно пропарсить три журнала: "Физика" (не используется из-за различия программ и кол-ва уроков), "Физика (рус- мат)" и "Физика (физ - мат)") и понять, в каком же из этих журналов таки учится конкретный ученик, после чего из ужасно структурированного журнала вычленить таки ID урока и ID журнала. Итог: 3 запроса с потреблением процессорного времени на парсинг против 1 запроса к API Schools.by, которое всю необходимую информацию возвращает в одном запросе. (Кстати, для проектов для мобильных устройств добавляется ещё один фактор не в пользу парсинга: мобильный трафик).
3. Аунтефикация в API намного более стабильная, чем в веб-версии - по неким причинам, известным только самим разработчикам Schools.by, токен из API постоянный - один неистекающий токен закреплён за каждым аккаунтом, что гораздо проще куки, которые меняются после смены пароля/логина/истечения срока действия/по щучьему велению. (Не скажу, что это хорошо для безопасности самого сервиса, но в чистом сравнении парсинга и API выигрывает последний).

Прошу прощения за лонгрид, просто хотел поделиться, зачем API :)

**Comment by TimTProd** [comment]
Ну если нет выбора то приходиться использовать костыли. И на счет куки: аутентификация на сайте то тупорылая: без двухфакторной аутентификации и даже хотя бы без проверки на робота. Это я к тому что можно не мучаться а просто логиниться каждый раз) Даже никакого кулдауна нет на логин, можно очень часто это делать

**Comment by Neitex** [comment]
Я бы не сказал, что в потребительском софте логин на каждую пачку запросов можно считать хорошей практикой :)
Да и пароли с логинами могут меняться, а токен - вечный (не знаю, хорошо ли это или плохо).

А вообще, если рассматривать сервис публичный, то хранить пароли пользователей - дело очень непростое и опасное (см. https://youtu.be/8ZtInClXe1Q).

**Comment by TimTProd** [comment]
Ну так ведь тут речь не про сервис с датабазой, тут конкретно скрипт на устройстве обращается к серверу, хранится всё локально на устройстве

**Comment by Neitex** [comment]
Доля правды есть, но в любом случае хранить неизменный токен проще, чем каждый раз логиниться и гадать, таки залогинилось или куки истекли :)
Считаю тему исчерпавшей себя (ишью я таки закрыл 2-го ноября 2021, что было чуть больше полугода назад) и всем, кто интересовался темой понятно, что API свободного Schools.by не предоставит :)
